use shared::models::*;
use std::path::PathBuf;

/// Write terraform files to disk for a build
pub fn write_build_files(build: &Build) -> Result<(), leptos::ServerFnError> {
    let dir = get_build_dir(build);
    std::fs::create_dir_all(&dir)
        .map_err(|e| leptos::ServerFnError::<leptos::server_fn::error::NoCustomError>::ServerError(format!("mkdir failed: {}", e)))?;

    let main_tf = generate_main_tf(build);
    let tfvars = generate_tfvars(build);
    let variables_tf = generate_variables_tf(build);

    std::fs::write(dir.join("main.tf"), &main_tf)
        .map_err(|e| leptos::ServerFnError::<leptos::server_fn::error::NoCustomError>::ServerError(format!("write: {}", e)))?;
    std::fs::write(dir.join("terraform.tfvars"), &tfvars)
        .map_err(|e| leptos::ServerFnError::<leptos::server_fn::error::NoCustomError>::ServerError(format!("write: {}", e)))?;
    std::fs::write(dir.join("variables.tf"), &variables_tf)
        .map_err(|e| leptos::ServerFnError::<leptos::server_fn::error::NoCustomError>::ServerError(format!("write: {}", e)))?;

    Ok(())
}

pub fn get_build_dir(build: &Build) -> PathBuf {
    PathBuf::from("deployments")
        .join(build.build_type.to_string().to_lowercase())
        .join(&build.name)
}

fn generate_main_tf(build: &Build) -> String {
    let provider = format!(r#"# Generated by infra-job-killer
# Build: {} | Region: {} | Env: {}

terraform {{
  required_version = ">= 1.5"
  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }}
  }}
}}

provider "aws" {{
  region = var.region
}}

"#, build.name, build.region, build.environment);

    let resources = match &build.config {
        BuildConfig::Vpc(c) => vpc_resources(c),
        BuildConfig::Ec2(c) => ec2_resources(c),
        BuildConfig::Ebs(c) => ebs_resources(c),
        BuildConfig::Eks(c) => eks_resources(c),
    };

    format!("{}{}", provider, resources)
}

fn generate_tfvars(build: &Build) -> String {
    let mut out = format!("# Generated by infra-job-killer\nregion = \"{}\"\n\n", build.region);
    match &build.config {
        BuildConfig::Vpc(c) => {
            out.push_str(&format!("vpc_cidr           = \"{}\"\n", c.vpc_cidr));
            out.push_str(&format!("az_count           = {}\n", c.az_count));
            out.push_str(&format!("enable_nat_gateway = {}\n", c.enable_nat_gateway));
            out.push_str(&format!("single_nat_gateway = {}\n", c.single_nat_gateway));
            out.push_str(&format!("enable_flow_logs   = {}\n", c.enable_flow_logs));
        }
        BuildConfig::Ec2(c) => {
            out.push_str(&format!("instance_type   = \"{}\"\n", c.instance_type));
            out.push_str(&format!("instance_count  = {}\n", c.instance_count));
            out.push_str(&format!("volume_size_gb  = {}\n", c.volume_size_gb));
            out.push_str(&format!("volume_type     = \"{}\"\n", c.volume_type));
            out.push_str(&format!("monitoring      = {}\n", c.enable_monitoring));
        }
        BuildConfig::Ebs(c) => {
            out.push_str(&format!("volume_size = {}\n", c.volume_size_gb));
            out.push_str(&format!("volume_type = \"{}\"\n", c.volume_type));
            out.push_str(&format!("encrypted   = {}\n", c.encrypted));
            out.push_str(&format!("iops        = {}\n", c.iops.unwrap_or(3000)));
        }
        BuildConfig::Eks(c) => {
            out.push_str(&format!("cluster_name    = \"{}\"\n", c.cluster_name));
            out.push_str(&format!("cluster_version = \"{}\"\n", c.cluster_version));
            out.push_str(&format!("instance_type   = \"{}\"\n", c.instance_type));
            out.push_str(&format!("min_nodes       = {}\n", c.min_nodes));
            out.push_str(&format!("max_nodes       = {}\n", c.max_nodes));
            out.push_str(&format!("desired_nodes   = {}\n", c.desired_nodes));
        }
    }
    out
}

fn generate_variables_tf(build: &Build) -> String {
    let mut out = String::from("variable \"region\" { type = string }\n\n");
    match &build.config {
        BuildConfig::Vpc(_) => {
            out.push_str("variable \"vpc_cidr\" { type = string }\n");
            out.push_str("variable \"az_count\" { type = number }\n");
            out.push_str("variable \"enable_nat_gateway\" { type = bool }\n");
            out.push_str("variable \"single_nat_gateway\" { type = bool }\n");
            out.push_str("variable \"enable_flow_logs\" { type = bool }\n");
        }
        BuildConfig::Ec2(_) => {
            out.push_str("variable \"instance_type\" { type = string }\n");
            out.push_str("variable \"instance_count\" { type = number }\n");
            out.push_str("variable \"volume_size_gb\" { type = number }\n");
            out.push_str("variable \"volume_type\" { type = string }\n");
            out.push_str("variable \"monitoring\" { type = bool }\n");
        }
        BuildConfig::Ebs(_) => {
            out.push_str("variable \"volume_size\" { type = number }\n");
            out.push_str("variable \"volume_type\" { type = string }\n");
            out.push_str("variable \"encrypted\" { type = bool }\n");
            out.push_str("variable \"iops\" { type = number }\n");
        }
        BuildConfig::Eks(_) => {
            out.push_str("variable \"cluster_name\" { type = string }\n");
            out.push_str("variable \"cluster_version\" { type = string }\n");
            out.push_str("variable \"instance_type\" { type = string }\n");
            out.push_str("variable \"min_nodes\" { type = number }\n");
            out.push_str("variable \"max_nodes\" { type = number }\n");
            out.push_str("variable \"desired_nodes\" { type = number }\n");
        }
    }
    out
}

fn vpc_resources(_c: &VpcConfig) -> String {
    r#"resource "aws_vpc" "main" {
  cidr_block           = var.vpc_cidr
  enable_dns_hostnames = true
  enable_dns_support   = true

  tags = { Name = "infra-job-killer-vpc" }
}

resource "aws_subnet" "private" {
  count             = var.az_count
  vpc_id            = aws_vpc.main.id
  cidr_block        = cidrsubnet(var.vpc_cidr, 4, count.index)
  availability_zone = data.aws_availability_zones.available.names[count.index]

  tags = { Name = "private-${count.index}" }
}

resource "aws_subnet" "public" {
  count                   = var.az_count
  vpc_id                  = aws_vpc.main.id
  cidr_block              = cidrsubnet(var.vpc_cidr, 4, count.index + var.az_count)
  availability_zone       = data.aws_availability_zones.available.names[count.index]
  map_public_ip_on_launch = true

  tags = { Name = "public-${count.index}" }
}

data "aws_availability_zones" "available" { state = "available" }

output "vpc_id" { value = aws_vpc.main.id }
output "private_subnet_ids" { value = aws_subnet.private[*].id }
output "public_subnet_ids" { value = aws_subnet.public[*].id }
"#.to_string()
}

fn ec2_resources(_c: &Ec2Config) -> String {
    r#"data "aws_ami" "al2023" {
  most_recent = true
  owners      = ["amazon"]
  filter {
    name   = "name"
    values = ["al2023-ami-*-x86_64"]
  }
}

resource "aws_instance" "this" {
  count         = var.instance_count
  ami           = data.aws_ami.al2023.id
  instance_type = var.instance_type
  monitoring    = var.monitoring

  root_block_device {
    volume_size = var.volume_size_gb
    volume_type = var.volume_type
    encrypted   = true
  }

  tags = { Name = "infra-job-killer-${count.index}" }
}

output "instance_ids" { value = aws_instance.this[*].id }
output "private_ips" { value = aws_instance.this[*].private_ip }
"#.to_string()
}

fn ebs_resources(_c: &EbsConfig) -> String {
    r#"resource "aws_ebs_volume" "this" {
  availability_zone = "${var.region}a"
  size              = var.volume_size
  type              = var.volume_type
  encrypted         = var.encrypted
  iops              = var.volume_type == "gp3" ? var.iops : null

  tags = { Name = "infra-job-killer-vol" }
}

output "volume_id" { value = aws_ebs_volume.this.id }
"#.to_string()
}

fn eks_resources(_c: &EksConfig) -> String {
    r#"# EKS requires VPC + IAM — full module composition
# This is a simplified version for the demo

resource "aws_eks_cluster" "this" {
  name     = var.cluster_name
  version  = var.cluster_version
  role_arn = aws_iam_role.cluster.arn

  vpc_config {
    endpoint_private_access = true
    endpoint_public_access  = true
  }

  tags = { Name = var.cluster_name }
}

resource "aws_iam_role" "cluster" {
  name = "${var.cluster_name}-cluster-role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = { Service = "eks.amazonaws.com" }
    }]
  })
}

resource "aws_iam_role_policy_attachment" "cluster" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
  role       = aws_iam_role.cluster.name
}

output "cluster_endpoint" { value = aws_eks_cluster.this.endpoint }
output "cluster_name" { value = aws_eks_cluster.this.name }
"#.to_string()
}
